services:
  postgres:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  proxy:
  #  command: ["-r", "postgres:5432", "-r", "mongo:27017", "-l", ":2143"]
    command: ["-r", "postgres:5432", "-l", ":2143"]
    build: .
    ports:
      - 80:80
      - 2143:2143

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt